name: Publish Site

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - uses: addnab/docker-run-action@v3
        with:
          image: peterdavehello/opencc:latest
          options: -v ${{ github.workspace }}:/repo -w /repo
          run: |
            /repo/scripts/opencc.sh
      - run: npm ci
      - run: hugo --minify
        env:
          HUGO_DISABLELANGUAGES: 'en'
      - run: npx wrangler pages deploy public --project-name tfsci --branch main
        if: github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
